### ISSUE TITLE
Team Awesome Opossum

### ISSUE THREAD

**Issue by etnt93** [HackCU/HackCUSpring2015_teamSignups#12]
etnt93
jprahladan
kellyegoodman

**Comment by ianks** [comment]
GitHub usernames plz :heart:

**Comment by etnt93** [comment]
etnt93jprahladankellyegoodman 


     On Friday, April 10, 2015 6:57 PM, Ian Ker-Seymer <notifications@github.com> wrote:
   

 GitHub usernames plz —

**Comment by etnt93** [comment]
etnt93
jprahladan
kellyegoodman
