### ISSUE TITLE
Team 01

### ISSUE THREAD

**Issue by ghost** [HackCU/HackCUSpring2015_teamSignups#4]
Dragos Iarovoi, Srinjita Bhaduri, Jeeeun Kim

**Comment by ianks** [comment]
GitHub usernames plz :smile:

**Comment by ghost** [comment]
dragos iarovoi - dria7226

**Comment by Srinjita** [comment]
Srinjita Bhaduri- Srinjita

**Comment by ghost** [comment]
Jeeeun Kim - qubick

**Comment by bifur-cation** [comment]
Derek Gann - DirtyD33

**Comment by CaptainAtlas** [comment]
Renamed to ZeroOne for script use.
