### ISSUE TITLE
Team RateMyBuffs

### ISSUE THREAD

**Issue by simmeringc** [HackCU/HackCUSpring2015_teamSignups#8]
Chrome and Safari extension that makes choosing UCB courses easy by retrieving class and professor ratings from cufcq.com and displaying them in the mycu registration page.

**Comment by simmeringc** [comment]
Usernames:

simmeringc
JustinWayneOlson

**Comment by untra** [comment]
sup. I made cufcq. Where you dawgs at?

**Comment by simmeringc** [comment]
Usernames:

simmeringc
JustinWayneOlson
untra
